ural_treats/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove_from_cart/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('cart/', views.cart, name='cart'),
    path('orders/', views.order_history, name='order_history'),
]

ural_treats/main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index_view, name='index'),
    path('dilevery', views.delivery, name='delivery'),
    path('blog', views.blog, name='blog'),
    path('contacts', views.contacts, name='contacts')
]

ural_treats/products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('', views.catalog, name='catalog'),
    path('<slug:category_slug>/', views.catalog, name='index'),
    path('product/<slug:product_slug>/', views.product, name='product'),
]

ural_treats/ural_treats/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('users.urls', namespace='users')),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('products.urls', namespace='catalog')),
    path('cart/', include('cart.urls', namespace='cart')),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
 

ural_treats/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('signup/', views.signup, name='signup'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logout_view, name='logout'),
]

ural_treats/templates/includes/footer.html
{% load static %}
<footer class="main-footer">
    <div class="footer-container">
        <div class="footer-column">
            <img width="102" height="102" src={% static 'img/logo.svg' %} alt="логотип спорт магазина урал">
            <a href="tel:88000000000">8 800 000 00 00</a>
            <a href="mailto:Sale@uraltreats.ru">Sale@uraltreats.ru</a>
            <p>Екатеринбург, ул. Металлургов, д. 87, ТЦ “МЕГА”</p>
        </div>
        <ul class="footer-navigation-topics">
            <li class="footer-navigation-catalog">
                <h2>Каталог</h2>
                <ul class="footer-navigation">
                    <li class="footer-navigation-item">
                        <a href="#">Протеин</a>
                    </li>
                    <li class="footer-navigation-item">
                        <a href="#">Креатин</a>
                    </li>
                    <li class="footer-navigation-item">
                        <a href="#">Изотоники</a>
                    </li>
                    <li class="footer-navigation-item">
                        <a href="#">Гейнеры</a>
                    </li>
                    <li class="footer-navigation-item">
                        <a href="#">Шейкеры</a>
                    </li>
                    <li class="footer-navigation-item">
                        <a href="#">Батончики протеиновые</a>
                    </li>
                    <li class="footer-navigation-item">
                        <a href="#">L-карнитин</a>
                    </li>
                    <li class="footer-navigation-item">
                        <a href="#">Аминокислоты</a>
                    </li>
                    <li class="footer-navigation-item">
                        <a href="#">Напитки спортивные</a>
                    </li>
                </ul>
            </li>
            <li class="footer-navigation-info">
                <h2>Информация</h2>
                <ul class="footer-navigation">
                    <li class="footer-navigation-item">
                        <a href="{% url 'main:delivery' %}">Доставка и Оплата</a>
                    </li>
                    <li class="footer-navigation-item">
                        <a href="#">Конфиденциальность</a>
                    </li>
                    <li class="footer-navigation-item">
                        <a href="{% url 'main:contacts' %}">Контакты</a>
                    </li>
                    <li class="footer-navigation-item">
                        <a href="{% url 'main:blog' %}">Блог</a>
                    </li>
                    <li class="footer-navigation-item">
                        <a href="#">Возврат</a>
                    </li>
                </ul>
            </li>
            <li class="footer-navigation-social">
                <h2>Мы в социальных сетях</h2>
                <ul class="footer-navigation-soc">
                    <li class="footer-navigation-item">
                        <a class="social telegram" href="#"><img width="14" height="12" src={% static 'img/telegram.svg' %} alt="ссылка на телеграмм"></a>
                    </li>
                    <li class="footer-navigation-item">
                        <a class="social whatsapp" href="#"><img width="15" height="15" src={% static 'img/whatsapp.svg' %} alt="ссылка на ватсап"></a>
                    </li>
                    <li class="footer-navigation-item">
                        <a class="social vk" href="#"><img width="15" height="8" src={% static 'img/vk.svg' %} alt="ссылка на вконтанке"></a>
                    </li>
                </ul>
            </li>
        </ul>
        <ul class="pay_systems">
            <li class="pay_systems_item">
                <img width="53.5" height="15.5" src={% static 'img/mir.svg' %} alt="мир">
            </li>
            <li class="pay_systems_item">
                <img width="68.4" height="21" src={% static 'img/visa.svg' %} alt="виза">
            </li>
            <li class="pay_systems_item">
                <img width="42" height="41.4" src={% static 'img/webmoney.svg' %} alt="вебмани">
            </li> 
            <li class="pay_systems_item">
                <img width="38" height="36" src={% static 'img/yandex.svg' %} alt="яндекс">
            </li>
            <li class="pay_systems_item">
                <img width="65" height="39" src={% static 'img/master_card.svg' %} alt="мастер кард">
            </li>
        </ul>
        <p class="copyright">© Все права защищены.</p>
    </div>
</footer>

ural_treats/templates/includes/header.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Rubik:ital,wght@0,300..900;1,300..900&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bellota+Text:wght@700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href={% static 'css/style.css' %}>
    <title>SPORT SHOP URAL</title>
</head>
<body>
<header class="page_header">
    <div class="services">
        <div class="services_content">
            <p class="location">Екатеринбург</p>
            <a class="telephone" href="tel:88000000000">8 800 000 00 00</a>
        </div>
    </div>
    <nav class="main-nav">
        <a href="{% url 'main:index' %}">
            <img width="86" height="90" src="{% static 'img/logo.svg' %}" alt="логотип спорт магазина урал">
        </a>        
        <ul class="site-nav">
            <li class="site-nav-item">
                <a href="{% url 'products:catalog' %}">Каталог</a>
            </li>
            <li class="site-nav-item">
                <a href="{% url 'main:delivery' %}">Доставка и Оплата</a>
            </li>
            <li class="site-nav-item">
                <a href="{% url 'main:contacts' %}">Контакты</a>
            </li>
            <li class="site-nav-item">
                <a href="{% url 'main:blog' %}">Блог</a>
            </li>
        </ul>
        <ul class="toolbar-nav">
            <li class="toolbar-nav-item">
                {% if user.is_authenticated %}
                    <a href="{% url 'users:profile' %}">
                {% else %}
                    <a href="{% url 'users:login' %}">
                {% endif %}
                    <img width="24" height="24" src={% static 'img/profile.svg' %} alt="Иконка пользователя">
                </a>
            </li>
            <li class="toolbar-nav-item">
                <a href="{% url 'cart:cart' %}">
                    <img width="24" height="24" src={% static 'img/cart.svg' %} alt="Корзина покупателя">
                </a>
            </li>
        </ul>
    </nav>
</header>