ural_treats/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove_from_cart/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('cart/', views.cart, name='cart'),
    path('orders/', views.order_history, name='order_history'),
]

ural_treats/products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('', views.catalog, name='catalog'),
    path('<slug:category_slug>/', views.catalog, name='index'),
    path('product/<slug:product_slug>/', views.product, name='product'),
]

ural_treats/ural_treats/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('users.urls', namespace='users')),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('products.urls', namespace='catalog')),
    path('cart/', include('cart.urls', namespace='cart')),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
 

ural_treats/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('signup/', views.signup, name='signup'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logout_view, name='logout'),
]

ural_treats/templates/account.html
<!DOCTYPE html>
<html lang="ru">
{% load static %}
{% include 'includes/header.html' %}
<main>
    <article class="account">
        <h1 class="account_h1">Вход в личный кабинет</h1>
        <form action="" method="post" class="form">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    {{ field }}
                    {{ field.errors }}
                </div>
            {% endfor %}
            <button class="form-button" type="submit">Войти</button>
            <p class="form-new">Еще нет аккаунта? <a href="{% url 'users:signup' %}" class="form-new-create">Зарегистрироваться!</a></p>
        </form>
    </article>
</main>
{% include 'includes/footer.html' %}
</body>
</html>

ural_treats/templates/blog.html
{%load static%}
<!DOCTYPE html>
<html lang="ru">

{% include 'includes/header.html' %}

    <main>
        <div class="h2_blog" style="color: black; font-size: 80px; font-family: Roboto; font-weight: 700; line-height: 160px; word-wrap: break-word">Блог</div>
        <div class="blog_containeer">
        <div>
            <img src={% static 'img/image_32.png' %} alt="">
            <div style="width: 520px; color: #D785A1; font-size: 22px; font-family: Roboto; font-weight: 400; line-height: 33px; word-wrap: break-word">Метаболический синдром</div>
    <div style="width: 520px; height: 71px; color: #636363; font-size: 16px; font-family: Roboto; font-weight: 400; line-height: 24px; word-wrap: break-word">Метаболический синдром – это собирательный диагноз, представляющий серьёзную опасность для здоровья человека</div>
        </div>
        <div>
            <img src={% static 'img/image_33.png' %} alt="">
    <div style="width: 520px; color: black; font-size: 22px; font-family: Roboto; font-weight: 400; line-height: 33px; word-wrap: break-word">Профилактика возрастных изменений костных и соединительных тканей<br/></div>
<div style="width: 520px; height: 71px; color: #636363; font-size: 16px; font-family: Roboto; font-weight: 400; line-height: 24px; word-wrap: break-word">Всем нам хочется дольше оставаться молодыми, крепкими, здоровыми и красивыми. А стареть никто не хочет.</div>
        </div>
    <div>
        <img src={% static 'img/image_34.png' %} alt="">
    <div style="width: 520px; color: black; font-size: 22px; font-family: Roboto; font-weight: 400; line-height: 33px; word-wrap: break-word">Необходимость соблюдать питьевой режим<br/></div>
<div style="width: 520px; height: 71px; color: #636363; font-size: 16px; font-family: Roboto; font-weight: 400; line-height: 24px; word-wrap: break-word">Питьевой режим – это потребность в чистой питьевой воде течение дня с учётом внешних факторов и уровня физической активности.</div>
    </div>
    <div>
        <img src={% static 'img/image_35.png' %} alt="">
        <div style="width: 520px; color: black; font-size: 22px; font-family: Roboto; font-weight: 400; line-height: 33px; word-wrap: break-word">Мышечные судороги, их причины и как с ними бороться<br/></div>
    <div style="width: 520px; height: 71px; color: #636363; font-size: 16px; font-family: Roboto; font-weight: 400; line-height: 24px; word-wrap: break-word">Каждый человек в своей жизни сталкивался с такой жалобой как судороги в ногах. Чаще подобное бывает у людей с высокой физической активностью и у спортсменов.</div>
    </div>
    
    <div>
        <img src={% static 'img/Rectangle_117.png' %} alt="">
    <div style="width: 520px; color: black; font-size: 22px; font-family: Roboto; font-weight: 400; line-height: 33px; word-wrap: break-word">Витамины и добавки для нормализации микрофлоры кишечника</div>
<div style="width: 520px; height: 71px; color: #636363; font-size: 16px; font-family: Roboto; font-weight: 400; line-height: 24px; word-wrap: break-word">Современная наука довольно многое знает о человеческом организме. Как он работает, что на него влияет плохо, а что хорошо, что укрепляет, а что истощает его ресурсы.</div>
    </div>
    <div>
        <img src={% static 'img/Rectangle_118.png' %} alt="">
    <div style="width: 520px; color: black; font-size: 22px; font-family: Roboto; font-weight: 400; line-height: 33px; word-wrap: break-word">Дополнительный прием аминокислот при стрессе и тревожности<br/></div>
<div style="width: 520px; height: 71px; color: #636363; font-size: 16px; font-family: Roboto; font-weight: 400; line-height: 24px; word-wrap: break-word">Существует мнение, что тревожность может быть устранена только лекарственными веществами.</div>
    </div>
</div>

</main>
{% include 'includes/footer.html' %}

</body>

</html>

ural_treats/templates/catalog.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">

{% include 'includes/header.html' %}

<body>
    <main>
        <div class="catalog_container">
            <div class="catalog_h2" style="color: #757575; font-size: 14px; font-family: Roboto; font-weight: 400; line-height: 28px; word-wrap: break-word">
                Главная / Каталог
            </div>
            
            <form method="get" action="{% url 'products:catalog' %}" class="search-form">
                <input type="text" name="q" placeholder="Поиск товаров..." value="{{ request.GET.q }}">
                <button type="submit"><img src="{% static 'img/search.svg' %}" alt="Поиск"></button>
            </form>

            <a href="?order_by=price">Сортировать по цене</a>
            <a href="?order_by=name">Сортировать по имени</a>

            <div>
                <h2>Категории</h2>
                <ul>
                    <li><a href="{% url 'products:catalog' %}">Все</a></li>
                    {% for category in categories %}
                        <li>
                            <a href="{% url 'products:index' category.slug %}" 
                               {% if category.slug == selected_category %}class="selected"{% endif %}>
                               {{ category.name }}
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
            

            <div class="products" style="display: flex; flex-wrap: wrap;">
                {% for product in products %}
                    <div class="product" style="width: 300px; margin: 10px;">
                        <a href="{{ product.get_absolute_url }}">
                            <img width="300" height="300" src="{{ product.image.url }}" alt="{{ product.name }}">
                            <h3>{{ product.name }}</h3>
                            <p>{{ product.price }} руб.</p>
                        </a>
                    </div>
                {% endfor %}
            </div>

            {% if products.has_other_pages %}
                <div class="pagination">
                    {% if products.has_previous %}
                        <a href="?page=1"><<</a>
                        <a href="?page={{ products.previous_page_number }}">Предыдущая</a>
                    {% endif %}
                    <span class="current">Страница {{ products.number }} из {{ products.paginator.num_pages }}</span>
                    {% if products.has_next %}
                        <a href="?page={{ products.next_page_number }}">Следующая</a>
                        <a href="?page={{ products.paginator.num_pages }}">>></a>
                    {% endif %}
                </div>
            {% endif %}
        </div>
    </main>

    {% include 'includes/footer.html' %}

</body>
</html>

ural_treats/templates/contacts.html
{%load static%}
<!DOCTYPE html>
<html lang="ru">

{% include 'includes/header.html' %}

    <main>
        <div>
            <div style="width: 595px; height: 229px; position: relative">
                <div style="width: 595px; height: 229px; left: 0px; top: 0px; position: absolute; background: #F3F3F3">
                </div>
                <div style="left: 65px; top: 34px; position: absolute"><span
                        style="color: #828282; font-size: 16px; font-family: Roboto; font-weight: 400; line-height: 32px; word-wrap: break-word">Магазин<br /></span><span
                        style="color: black; font-size: 16px; font-family: Roboto; font-weight: 700; line-height: 32px; word-wrap: break-word">Екатеринбург,
                        Улица Металлургов, д. 87, ТЦ “Мега”</span><span
                        style="color: black; font-size: 16px; font-family: Roboto; font-weight: 400; line-height: 32px; word-wrap: break-word">
                        <br /></span><span
                        style="color: #F10D48; font-size: 16px; font-family: Roboto; font-weight: 400; line-height: 32px; word-wrap: break-word">UralTreatsShop.ru
                        <br />Sale@uraltreats.ru
                        <br /></span><span
                        style="color: black; font-size: 18px; font-family: Roboto; font-weight: 400; line-height: 36px; word-wrap: break-word">+7
                        800 00 00 00</span></div>
            </div>
            <div style="left: 650px; top: -230px; position: relative">
                <rect width="12" height="1080" fill="#ECECEC" />
                <rect x="2" y="5.00586" width="8" height="117.136" rx="4" fill="#5C5C66" />
              </svg>
    
            <img style="width: 1189px; height: 1117px" src={% static 'img/map.jpg' %} />
        </div>
        </div>
    </main>
    {% include 'includes/footer.html' %}

</body>

</html>

ural_treats/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">

{% include 'includes/header.html' %}


<body class="page">
    <main class="main-content">
        <section class="hero">
            <div class="hero_info">
                <h1>URAL TREATS</h1>
                <p>Специальные цены только до 30 июня</p>
                <a href="{% url 'products:catalog' %}"><button class="hero_btn">Перейти в каталог <img src={% static 'img/vector.svg' %} alt=""></button></a>
            </div>
            <img class="hero_model1" width="434" height="660" src={% static 'img/hero_model1.png' %} alt="">
            <img class="hero_model2" width="434" height="660" src={% static 'img/hero_model2.png' %} alt="">
        </section>


        <section class="promotion">
            <div class="promotion_main">
                <img width="784" height="357" src={% static 'img/gaba.jpg' %} alt="">
                <div class="promotion_info">
                    <h2>
                        GABA, 700 мг 90 капсул по 833 мг,
                        Гамма аминомасляная кислота, способствует улучшению памяти и
                        качества
                        сна, от стресса
                    </h2>
                    <p>
                        GABA (гамма-аминомасляная кислота) – непротеиногенная аминокислота,
                        тормозной нейромедиатор центральной нервной системы.<br>
                        Принимает участие в регуляторных и метаболических процессах в мозге.<br>
                        Ноотропное средство,участвует в метаболизме глюкозы и тканевом дыхании.
                    </p>
                    <a href="http://127.0.0.1:8000/catalog/product/gaba-700-mg-90-kapsul-po-833-mg-gamma-aminomaslyanaya-kislota/">Подробнее <img src={% static 'img/promotion_vector.svg' %} alt=""></a>
                </div>

            </div>
            <ul class="promotion-list">
                <li class="promotion-list-item">
                    Безупречный состав<br>
                    и эффективность
                </li>
                <li class="promotion-list-item">
                    Натуральность и<br>
                    экологичность
                </li>
                <li class="promotion-list-item">
                    Наличный<br>
                    и безналичный расчет
                </li>
                <li class="promotion-list-item">
                    Доставка<br>
                    по всей России
                </li>
            </ul>
        </section>

        <section class="new_product">
            <div class="new_product_head">
                <h2>Новинки</h2>
            </div>
            <ul class="cards">
                <li class="card">
                    <div class="card_container_img">
                        <img width="377" height="400" src={% static 'img/Soulway.jpg' %} alt="Протеин Soulway">
                    </div>
                    <div class="card_container_info">
                        <h3 class="card_title">Протеин Soulway 900 г</h3>
                        <p class="card_description">Клубника</p>
                        <p class="card_price">4490 руб</p>
                    </div>
                </li>
                <li class="card">
                    <div class="card_container_img">
                        <img width="377" height="400" src={% static 'img/PRIMECRAFT.jpg' %} alt="Протеин PRIMECRAFT">
                    </div>
                    <div class="card_container_info">
                        <h3 class="card_title">Протеин PRIMECRAFT 900г</h3>
                        <p class="card_description">Белый шоколад с клубникой</p>
                        <p class="card_price">3 490 руб</p>
                    </div>
                </li>
                <li class="card">
                    <div class="card_container_img">
                        <img width="303" height="137" src={% static 'img/Bombbar.jpg' %} alt="Батончик протеиновый Bombbar">
                    </div>
                    <div class="card_container_info">
                        <h3 class="card_title">Батончик протеиновый Bombbar</h3>
                        <p class="card_description">Фисташечная меренга</p>
                        <p class="card_price">179 руб</p>
                    </div>
                </li>
                <li class="card">
                    <div class="card_container_img">
                        <img width="377" height="400" src={% static 'img/SPORTINA.jpg' %} alt="Напиток SPORTINA">
                    </div>
                    <div class="card_container_info">
                        <h3 class="card_title">Напиток SPORTINA</h3>
                        <p class="card_description">Апельсин, яблоко, груша</p>
                        <p class="card_price">149 руб</p>
                    </div>
                </li>
            </ul>
        </section>

        <section class="sale_product">
            <div class="sale_product_head">
                <h2>Акционные товары</h2>
            </div>
            <ul class="cards">
                <li class="card">
                    <div class="sale_card_container">
                        <img width="473" height="492" src={% static 'img/GABA_GLS.jpg' %} alt="Maxler Creatine">
                    </div>
                    <div class="sale_card_info">
                        <h3 class="card_title">GABA GLS</h3>
                        <p class="card_description">Гамма-аминомасляная кислота</p>
                    </div>
                </li>
                <li class="card">
                    <div class="sale_card_container">
                        <img width="346" height="419" src={% static 'img/Maxler_Creatine.jpg' %} alt="Maxler Creatine">
                    </div>
                    <div class="sale_card_info">
                        <h3 class="card_title">Maxler Creatine</h3>
                        <p class="card_description">Креатин моногидрат</p>
                    </div>
                </li>
            </ul>
        </section>

        <section class="recomendation_product">
            <div class="recomendation_product_head">
                <h2>Рекомендуемые товары</h2>
            </div>
            <ul class="cards">
                <li class="card">
                    <div class="card_container_img">
                        <img src={% static 'img/BCAA_411_COMPLEX.jpg' %} alt="Протеин Soulway">
                    </div>
                    <div class="card_container_info">
                        <h3 class="card_title">BCAA 4:1:1 COMPLEX ATECH</h3>
                        <p class="card_description">240 капсул</p>
                        <p class="card_price">2 480 руб</p>
                        <span class="card_price_old">3579 руб</span>
                    </div>
                </li>
                <li class="card">
                    <div class="card_container_img">
                        <img src={% static 'img/BCAA_211_PRIMECRAFT.jpg' %} alt="BCAA 2:1:1 PRIMECRAFT">
                    </div>
                    <div class="card_container_info">
                        <h3 class="card_title">BCAA 2:1:1 PRIMECRAFT</h3>
                        <p class="card_description">240 капсул</p>
                        <p class="card_price">2 480 руб</p>
                    </div>
                </li>
                <li class="card">
                    <div class="card_container_img">
                        <img src={% static 'img/BCAA_211.jpg' %} alt="BCAA 2:1:1">
                    </div>
                    <div class="card_container_info">
                        <h3 class="card_title">BCAA 2:1:1</h3>
                        <p class="card_description">90 капсул</p>
                        <p class="card_price">2 480 руб</p>
                    </div>
                </li>
                <li class="card">
                    <div class="card_container_img">
                        <img src={% static 'img/BCAA_211_instant.jpg' %} alt="BCAA 2:1:1 INSTANT">
                    </div>
                    <div class="card_container_info">
                        <h3 class="card_title">BCAA 2:1:1</h3>
                        <p class="card_description">200 капсул</p>
                        <p class="card_price">2 480 руб</p>
                        <span class="card_price_old">3579 руб</span>
                    </div>
                </li>
            </ul>
        </section>
        <section class="mailing">
            <img width="789" height="557" src={% static 'img/mailing_image.jpg' %} alt="изображение цветка">
            <div class="mailing_content">
                <h2>Подпишитесь на рассылку</h2>
                <p>Узнай первым о старте скидок и специальных  предложений!</p>
                <form action="" method="POST">
                    <input type="email" placeholder="Введите почту">
                    <button type="submit">Подписаться</button>
                </form>
            </div>
        </section>
    </main>

    {% include 'includes/footer.html' %}

</body>

</html>

ural_treats/templates/productPage.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
{% include 'includes/header.html' %}
<main class="main-content">
    <p class="main-direction">Главная / Каталог / {{ product.category.name }}</p>
    <div class="basic-information">
        <img width="479" height="504" src="{{ product.image.url }}" alt="{{ product.name }}">
        <div class="basic-description">
            <h2 class="product-title">{{ product.name }}</h2>
            <form method="post" action="{% url 'cart:add_to_cart' product.id %}">
                {% csrf_token %}
                <label for="quantity">Количество:</label>
                <input type="number" id="quantity" name="quantity" value="1" min="1" max="{{ product.quantity }}">
                <p class="price">{{ product.price }} руб</p>
                <button type="submit" class="form-button">Добавить в корзину</button>
                <div class="description">
                    {{ product.description }}
                </div>
            </form>
        </div>
    </div>
    <section class="recomendation_product"> 
        <div class="recomendation_product_head">
            <h2>Рекомендуемые товары</h2>
        </div>
        <ul class="cards">
            <li class="card">
                <div class="card_container_img">
                    <img src={% static 'img/BCAA_411_COMPLEX.jpg' %} alt="Протеин Soulway">
                </div>
                <div class="card_container_info">
                    <h3 class="card_title">Протеин сывороточный Soul Way</h3>
                    <p class="card_description">900 гр 30 порций</p>
                    <p class="card_price">1 106 руб</p>
                </div>
            </li>
            <li class="card">
                <div class="card_container_img">
                    <img src={% static 'img/BCAA_211_PRIMECRAFT.jpg' %} alt="BCAA 2:1:1 PRIMECRAFT">
                </div>
                <div class="card_container_info">
                    <h3 class="card_title">Протеин сывороточный tobePRO</h3>
                    <p class="card_description">900 гр 30 порций</p>
                    <p class="card_price">1 865 руб</p>
                </div>
            </li>
            <li class="card">
                <div class="card_container_img">
                    <img src={% static 'img/BCAA_211.jpg' %} alt="BCAA 2:1:1">
                </div>
                <div class="card_container_info">
                    <h3 class="card_title">Протеин PRIMEKRAFT</h3>
                    <p class="card_description">900 гр 30 порций</p>
                    <p class="card_price">2 480 руб</p>
                </div>
            </li>
            <li class="card">
                <div class="card_container_img">
                    <img src={% static 'img/BCAA_211_instant.jpg' %} alt="BCAA 2:1:1 INSTANT">
                </div>
                <div class="card_container_info">
                    <h3 class="card_title">Протеин сывороточный ELITE</h3>
                    <p class="card_description">900 гр 30 порций</p>
                    <p class="card_price">2 440 руб</p>
                </div>
            </li>
        </ul>
    </section>
    <section class="recomendation_product">
        <div class="recomendation_product_head">
            <h2>Похожие товары</h2>
        </div>
        <ul class="cards">
            <li class="card">
                <div class="card_container_img">
                    <img src={% static '/img/BCAA_411_COMPLEX.jpg' %} alt="Протеин Soulway">
                </div>
                <div class="card_container_info">
                    <h3 class="card_title">Креатин моногидрат BioPrime</h3>
                    <p class="card_description">200 гр / 40 порций</p>
                    <p class="card_price">846 руб</p>
                </div>
            </li>
            <li class="card">
                <div class="card_container_img">
                    <img src={% static '/img/BCAA_211_PRIMECRAFT.jpg' %} alt="BCAA 2:1:1 PRIMECRAFT">
                </div>
                <div class="card_container_info">
                    <h3 class="card_title">Моногидрат PRIMEKRAFT</h3>
                    <p class="card_description">200 гр / 40 порций</p>
                    <p class="card_price">2 480 руб</p>
                </div>
            </li>
            <li class="card">
                <div class="card_container_img">
                    <img src={% static '/img/BCAA_211.jpg' %} alt="BCAA 2:1:1">
                </div>
                <div class="card_container_info">
                    <h3 class="card_title">Креатин aTech Nutrition</h3>
                    <p class="card_description">120 капсул</p>
                    <p class="card_price">830 руб</p>
                </div>
            </li>
            <li class="card">
                <div class="card_container_img">
                    <img src={% static '/img/BCAA_211_instant.jpg' %} alt="BCAA 2:1:1 INSTANT">
                </div>
                <div class="card_container_info">
                    <h3 class="card_title">Креатин monohydrate</h3>
                    <p class="card_description">120 капсул</p>
                    <p class="card_price">527 руб</p>
                </div>
            </li>
        </ul>
    </section>
</main>
{% include 'includes/footer.html' %}

</body>

</html>

ural_treats/templates/profile.html
<!DOCTYPE html>
<html lang="ru">
{% load static %}
{% include 'includes/header.html' %}
<main>
    <article class="account profile">
        <div class="container-profile">
            <h2 class="profile-name">{{ user.first_name }} {{ user.last_name }}</h2>
            <ul class="profile-list">
                <li class="profile-item active">Личная информация</li>
                <li class="profile-item"> <a href="{% url 'cart:order_history' %}"> Мои покупки</li>
                <li class="profile-item">
                    <a href="{% url 'users:logout' %}">Выйти</a>
                </li>
            </ul>
        </div>
        <div>
            <h1 class="account_h1 prof">Личная информация</h1>
            <form action="" method="post" class="form">
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        {{ field }}
                        {{ field.errors }}
                    </div>
                {% endfor %}
                <div class="politic-container">
                    <input class="checkbox" type="checkbox" name="" id="">
                    <p class="politic">Я даю согласие на обработку своих персональных данных в соответствии с 
                        <span class="pol">Политикой в отношении обработки персональных данных</span> и 
                        <span class="pol">Пользовательским соглашением</span>.
                    </p>
                </div>
                <button class="form-button prof" type="submit">Сохранить</button> 
            </form>
        </div>
    </article>
</main>
{% include 'includes/footer.html' %}
</body

ural_treats/templates/registration.html
<!DOCTYPE html>
<html lang="ru">
{% load static %}
{% include 'includes/header.html' %}
<main>
    <article class="account">
        <h1 class="account_h1 reg">Регистрация</h1>
        <form action="" method="post" class="form">
            {% csrf_token %}
            {{ form.non_field_errors }}

            <div class="form-group">
                <input class="form-input lastName" type="text" placeholder="Фамилия" name="last_name">
                {{ form.last_name.errors }}
            </div>
            <div class="form-group">
                <input class="form-input name" type="text" placeholder="Имя" name="first_name">
                {{ form.first_name.errors }}
            </div>
            <div class="form-group">
                <input class="form-input mail" type="email" placeholder="Ваша почта" name="email">
                {{ form.email.errors }}
            </div>
            <div class="form-group">
                <input class="form-input tel" type="text" placeholder="Телефон" name="tel">
                {{ form.tel.errors }}
            </div>
            <div class="form-group">
                <input class="form-input pass" type="password" placeholder="Пароль" name="password1">
                {{ form.password1.errors }}
            </div>
            <div class="form-group">
                <input class="form-input pass_again" type="password" placeholder="Подтверждение пароля" name="password2">
                {{ form.password2.errors }}
            </div>
            <div class="politic-container">
                <input class="checkbox" type="checkbox" name="agree" id="agree">
                <p class="politic">Я даю согласие на обработку своих персональных данных в соответствии с 
                <span class="pol">Политикой в отношении обработки персональных данных</span> и <span class="pol">Пользовательским соглашением</span>.</p>
            </div>
            <button class="form-button reg" type="submit">Зарегистрироваться</button>
        </form>
    </article>
</main>
{% include 'includes/footer.html' %}
</body>
</html>

ural_treats/templates/shoppingBasket.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
{% include 'includes/header.html' %}
<main>
    <div class="container">
        <h2>Корзина</h2>
        {% if cart_items %}
            <form method="post" action="{% url 'cart:cart' %}">
                {% csrf_token %}
                <table class="cart-table">
                    <thead>
                        <tr>
                            <th>Товар</th>
                            <th>Количество</th>
                            <th>Цена за единицу</th>
                            <th>Итого</th>
                            <th>Удалить</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in cart_items %}
                            <tr>
                                <td>{{ item.product.name }}</td>
                                <td>{{ item.quantity }}</td>
                                <td>{{ item.product.price }}</td>
                                <td>{{ item.get_total_price }}</td>
                                <td>
                                    <form method="post" action="{% url 'cart:remove_from_cart' item.id %}">
                                        {% csrf_token %}
                                        <button type="submit">Удалить</button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <div class="cart-summary">
                    <p>Общая стоимость: {{ total_price }}</p>
                    <button type="submit">Оформить заказ</button>
                </div>
            </form>
        {% else %}
            <p>Ваша корзина пуста</p>
        {% endif %}
    </div>
</main>
{% include 'includes/footer.html' %}
</html>